name: test-and-publish
on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  build-test-merge-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        name: install node
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - uses: bbeesley/build-test-merge-publish@main
        with:
          main-branch: main
        env:
          WORKSPACE: ${{ github.workspace }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_PA_TOKEN }}
  lint-commits:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        name: install node
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - name: install
        run: npm i --package-lock=false @commitlint/cli @commitlint/config-conventional conventional-commit-types conventional-changelog-angular
      - name: commitlint
        run: ./node_modules/.bin/commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
